pipeline {
    environment {
        registry = ''
        dockerImage =''
        deploymentFile=''
    }
    agent any
    stages {
        stage("Test"){
            steps {
                withMaven {
                    sh 'mvn test'

                }

            }

        }

    }
}





}